### ISSUE TITLE
Analyze data from ALV/CGS-3 Goniometer device

### ISSUE THREAD

**Issue by weltsturz** [BAMresearch/analyse_dls_with_contin#1]
Hello!

I have a problem running the output files from the ALV/CGS-3 Goniometer device with your python script.
It seems that the "dlshelpers"-script can´t extract the correlation-data from the *.ASC-files generated by the DLS-System used at our university.
Would it be possible for you to upload an example-measurement, which you used to analyze with your script?
I´m sure that would help me a lot to resolve the problem.

with kind regards,
Vincent

**Comment by ibressler** [comment]
Hi Vincent,

thanks for your feedback! I am very interested in adding support for more data file variants. Of course, it is a good idea to add some data for testing purposes.

Recently, I added come test data with commit 16850933 and ran the notebooks with them, added the notebook outputs as well, for comparison. It's in [/testdata](https://github.com/BAMresearch/analyse_dls_with_contin/tree/main/testdata).

Soon, I will also add some code and a gh action for running and testing this.

If you are still having trouble, please feel free to provide some example data from your device so that I can fix the parser, shouldn't be that much different (suppose just a different control software version?)

Best wishes
Ingo

**Comment by weltsturz** [comment]
Thank you for the test data!
I got the software running with some slight modifications of the dlshelpers-file in the getDLSfiledata-segment. (attached file)
Additionally some measurement data are attached. (maybe you have a more elegant solution)

I also would be interested in plotting the decay time distribution instead of the hydrodynamic radius.
Is this possible? Because I`m really not sure how to modify the script in this way. (I am fairly new to python and especially matplotlib)

with kind regards,
Vincent
[dlshelpers2.zip](https://github.com/BAMresearch/analyse_dls_with_contin/files/9452307/dlshelpers2.zip)
[testdata_GCS3.zip](https://github.com/BAMresearch/analyse_dls_with_contin/files/9452326/testdata_GCS3.zip)

**Comment by ibressler** [comment]
Hi Vincent,

Thanks for your feedback and the proposed changes and your test data! That's very useful. I integrated your test data into the repository already, for running the tests with it as well.

The changes for more flexible switching between decay and radius distribution are already in the repo. getContinResults() returns the decay distrib now, since that's what CONTIN calculates in the first place. The gamma value required for converting it to a radius distrib. is return along in *varmap* by the same function. The notebook includes now the conversion to radius distrib. (as example) and the result plotting of all angles at the bottom can now be changed to decay or radius distrib. output.

I am working on adjusting the routine for reading the ASC files and I wonder what the 4 columns of correlation data mean in the data you provided? Do you know or do have any documentation about it? The first data column is the correlation, of course. But there is a second column with very similar (same?) but unequal values. The last two columns are zero - can they be ignored safely? I'd like to give it some meaningful names ;)

Thanks and best regards!
Ingo

Am 30.08.22 um 13:23 schrieb weltsturz:
> Thank you for the test data! I got the software running with some
> slight modifications of the dlshelpers-file in the
> getDLSfiledata-segment. (attached file) Additionally some measurement
> data are attached. (maybe you have a more elegant solution)
> 
> I also would be interested in plotting the decay time distribution
> instead of the hydrodynamic radius. Is this possible? Because I`m
> really not sure how to modify the script in this way. (I am fairly
> new to python and especially matplotlib)
> 
> with kind regards, Vincent dlshelpers2.zip
> <https://github.com/BAMresearch/analyse_dls_with_contin/files/9452307/dlshelpers2.zip>
>
> 
testdata_GCS3.zip <https://github.com/BAMresearch/analyse_dls_with_contin/files/9452326/testdata_GCS3.zip>

**Comment by ibressler** [comment]
With todays upload (b9dcfa307), it should now work with both file types. Also, the regression tests were updated and extended for the additional data. Please test and let me know which changes might be helpful.
Best regards!
Ingo

**Comment by ibressler** [comment]
Hi Vincent,

thank you for your feedback! I am very interested in adding support for 
more file types. Of course, it is a good idea to add some data for 
testing purposes.
Unfortunately, I am out of office at the moment. As soon as I am back at 
work (July 18 at the latest, probably), I'll look for some data which 
can be published here or was published elsewhere already.

Best wishes
Ingo

Am 05.07.22 um 15:06 schrieb weltsturz:

**Comment by weltsturz** [comment]
Hello Ingo,

the software works great!

The (very similiar) second column in the data is just another correlation data measurement due to the measurement mode I use. The zero containing columns can be ignored.
But I honestly do not know, if it would be better to use both columns for the evaluation for the data.

with kind regards,
Vincent

**Comment by leonardo-chiappisi** [comment]
Hi Ingo, 

the ALV has two APDs, and calculates two pseudo cross-correlation curves (signal1 with signal 2, and signal 2 with signal 1). What looks to me as the best option, is two average the two signals and work with the average. It improves significantly the data quality at short and long times. 

Hope this helps,
Leonardo

**Comment by ibressler** [comment]
> Hello Ingo,
> 
> the software works great!

Hi Vincent,

Great to hear that it works for you! Thanks for your feedback!

Best wishes
Ingo
